config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Custom routes
  get "workouts/my_workouts", to: "workouts#my_workouts"

  # Application routes
  resources :workouts, only: %i[index new create show destroy edit update] do
    resources :bookings, only: %i[new create] do
      resources :ratings, only: %i[new create]
    end
  end
  resources :users, only: [:show]
  resources :chats, only: [:index]

  resources :bookings, only: %i[index show destroy edit update] do
    resources :ratings, only: %i[new create]
    resources :chats, only: %i[show] do
      resources :messages, only: :create
    end
  end
end

# Defines the root path route ("/")
# root "articles#index"

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :ratings, through: :bookings
  has_one_attached :photo

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  validates :activity_type, :intensity_level, :location,
            :date, :start_time, :duration, :description, presence: true
  validates :intensity_level, numericality: { only_integer: true, in: 1..5 }
  validates :duration, numericality: { only_integer: true, greater_than_or_equal_to: 10, less_than_or_equal_to: 300 }
  validates :description, length: { minimum: 1 }

  scope :with_booking, -> { joins(:bookings) }
  scope :with_ratings, -> { joins(:ratings) }

  WORKOUT_EMOJIS = {
    'Run' => 'Run 🏃',
    'Walk' => 'Walk 🚶',
    'Cycle' => 'Cycle 🚴',
    'Strength' => 'Strength 🏋️',
    'Park Workout' => 'Park Workout 🌳',
    'Pilates Class' => 'Pilates Class 🧘',
    'Swim' => 'Swim 🏊',
    'Tennis' => 'Tennis 🎾',
    'Workout Class' => 'Workout Class 🏋️',
    'Yoga Class' => 'Yoga Class 🧘'
  }

  WORKOUT_INTENSITY = {
    1 => "Gentle",
    2 => "Less Gentle",
    3 => "Moderate",
    4 => "Fairly Intense",
    5 => "Hardcore"
  }

  def is_host?(logged_in_user)
    user == logged_in_user
  end

  def has_a_booking?
    bookings.any?
  end

  def has_a_rating?
    has_a_booking? ? bookings.first.ratings.any? : false
    # booking.any? { |booking| booking.ratings.any? }
  end

  def name_of_buddy(logged_in_user)
    is_host?(logged_in_user) ? (has_a_booking? ? bookings.first.user.first_name.capitalize : "buddy") : user.first_name.capitalize
  end

  def buddy(logged_in_user)
    is_host?(logged_in_user) ? (has_a_booking? ? bookings.first.user : "buddy") : user
  end

  def has_host_rating?
    bookings.first.ratings.any?(&:workout_host)
  end

  def has_guest_rating?
    bookings.first.ratings.any? { |r| r.workout_host == false }
  end

  def ask_for_rating?(logged_in_user)
    # workout should be in the past
    # workout should have a booking
    # logged in person (host OR booker) should not have given a rating already
    (date.past? && bookings.any? && ((is_host?(logged_in_user) && !has_host_rating?) || (!is_host?(logged_in_user) && !has_guest_rating?)))
  end

  def workout_chat
    Chat.where(booking_id: bookings.ids.first)
  end

  def self.chats
    chats = all.with_booking.map { |workout| workout.bookings.map(&:chat) }.flatten
    Chat.where(id: chats.map(&:id))
  end

  def self.ratings_by_others(logged_in_user)
    Rating.where(id: all.with_ratings.where.not('ratings.user_id' => logged_in_user.id).pluck('ratings.id'))
  end
end

app/controllers/workouts_controller.rb
require 'open-uri'

class WorkoutsController < ApplicationController
  before_action :set_user, only: %i[new create show destroy]
  before_action :set_booking, only: %i[show my_workouts]

  def new
    @workout = Workout.new
  end

  def create
    image = URI.open("https://hips.hearstapps.com/runnersworld-uk/i/16523/high_five.jpg")
    @workout = Workout.new(workout_params)
    @workout.user_id = current_user.id
    @workout.photo.attach(io: image, filename: "image", content_type: "image/png") unless @workout.photo.attached?
    if @workout.save
      redirect_to workout_path(@workout)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @workout = Workout.find(params[:id])
    @user.id = @workout.user_id
    @markers = [{
      lat: @workout.latitude,
      lng: @workout.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: {workout: @workout}),
      marker_html: render_to_string(partial: "marker", locals: {workout: @workout})
    }]
  end

  def index
    # The code below enables a filtered search
    # There is a listing class method to ensure that if search is nil, all Listings are displayed
    @workouts = Workout.where.missing(:bookings).order("workouts.date ASC")
    if params[:query].present?
      # sql_query = <<~SQL
      #   workouts.location ILIKE :query
      #   OR workouts.activity_type ILIKE :query
      #   OR workouts.intensity_level::text ILIKE :query
      #   OR users.first_name ILIKE :query
      # SQL
      # @workouts = Workout.joins(:user).where(sql_query, query: "%#{params[:query]}%")
      @workouts = @workouts.near(params[:query], 2)
      @search_copy = "#{@workouts.length} results near #{params[:query]}"
    end
    if params[:category].present?
      @workouts = @workouts.where(activity_type: params[:category])
      @search_copy = "#{@workouts.count} results for: #{params[:category]}"
    end
    @workout_location = @workouts.geocoded.map do |workout|
      {
        lat: workout.latitude,
        lng: workout.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {workout: workout}),
        marker_html: render_to_string(partial: "marker", locals: {workout: workout})
      }
    end
  end

  def my_workouts
    @my_workouts = Workout.where(user_id: current_user.id) if user_signed_in?
    @my_bookings = Booking.where(user_id: current_user.id) if user_signed_in?

    @all_workouts = []
    @my_bookings.each do |booking|
      @all_workouts.push(booking.workout)
    end
    @my_workouts.each do |workout|
      @all_workouts.push(workout)
    end

    @all_workouts.sort_by!(&:date)
    @upcoming_workouts = @all_workouts.reject { |workout| workout.date.past? }
    @past_workouts = @all_workouts.select { |workout| workout.date.past? }
  end

  def edit
    @workout = Workout.find(params[:id])
  end

  def update
    @workout = Workout.find(params[:id])
    @workout.update(workout_params)

    redirect_to workout_path(@workout)
  end

  def destroy
    @workout = Workout.find(params[:id])

    if @workout.destroy!
      redirect_to workouts_path, status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def set_booking
    @booking = Booking.new
  end

  def workout_params
    params.require(:workout).permit(:activity_type, :intensity_level, :location, :date,
                                    :start_time, :duration, :description, :capacity, :user_id, :photo)
  end
end

app/views/workouts/_form.html.erb
<div class="form-workout p-3">
    <%= simple_form_for(@workout) do |f| %>
            <%= f.input :activity_type, as: :select, collection: [
              'Cycle',
              'Strength',
              'Park Workout',
              'Pilates Class',
              'Run',
              'Swim',
              'Tennis',
              'Walk',
              'Workout Class',
              'Yoga Class'
              ], prompt: 'Select Activity',
              label: false %>
                <%= f.input :intensity_level,
                            as: :radio_buttons,
                            collection: [[1, 'Gentle'], [2, 'Less Gentle'], [3, 'Moderate'], [4, 'Fairly Intense'], [5, 'Hardcore']],
                            label_method: :second,
                            value_method: :first,
                            label: "Level of exertion",
                            required: true %>
            <%= f.input :location, placeholder: 'Location' %>
            <%= f.input :date, as: :date,
                        html5: true,
                        label: 'Date' %>
            <%= f.input :start_time,
                        label: 'Time',
                        default: Time.parse('10:00') %>
            <%= f.input :duration, placeholder: 'E.g. 30', label: 'Duration (mins)' %>
            <%= f.input :description, placeholder: 'Provide full details of the workout' %>
            <%= f.input :photo, as: :file %>
            <%= f.submit "Save workout", class: "button-design"%>
          <% end %>
</div>

app/views/workouts/_info_window.html.erb
<%= link_to workout_path(workout), style: "color: #2C302E;", class: "text-decoration-none" do %>
  <div class="d-flex flex-row justify-content-around">
    <div class="flex-fill">
      <h4 class="mb-0"><%= workout.activity_type %></h4>
      <p class="mb-0"><i class="fa-regular fa-user text-primary"></i> <%= workout.user.username %></p>
      <p class="mb-0"><i class="fa-regular fa-calendar text-primary"></i> <%= workout.date.strftime("%e %h %Y") %>, <%= workout.start_time.strftime("%H:%M") %></p>
      <p class="mb-0"><i class="fa-regular fa-clock text-primary"></i> <%= workout.duration %> mins</p>
    </div>
  </div>
<% end %>

app/views/workouts/_marker.html.erb
<%= cl_image_tag workout.user.photo.key, class: "avatar" %>

app/views/workouts/edit.html.erb
<div class="container pb-5 mb-4">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
    <%= link_to workouts_path do %>
      <div>
        <i class="fa-solid fa-arrow-left"></i>
      </div>
    <% end %>
      <div class="form-login">
          <h2>Amend Workout</h2>
            <div>
              <%= render "form", workout: @workout %>
            </div>
      </div>
    </div>
  </div>
</div>
</div>
  <%= render "shared/navbar_footer" %>
</div>

app/views/workouts/index.html.erb
<% provide(:title, "Workouts") %>

<div class="container pb-5 mb-4">
  <div class="container-white-workouts-list-search">
    <div class="d-flex flex-row justify-content-around align-items-center">
      <div class="p-1 bd-highlight flex-fill">
        <%= form_with url: workouts_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control me-1",
            placeholder: "🔍 Location"
          %>
          <%# <%= submit_tag "Go", class: "btn btn-outline-primary" %>
        <% end %>
      </div>
      <div class="flex-shrink-0">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item" role="presentation">
            <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">List</button>
          </li>
          <li class="nav-item" role="presentation">
            <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">Map</button>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
      <%# PAGE WITH WORKOUTS %>
      <div class="container-white-workouts-list-filter">
        <div class="d-flex flex-row justify-content-between align-items-center">
          <div class="my-1 text-center">
            <%= link_to workouts_path, style: "text-decoration: none" do %>
              <div>
                <i class="fa-solid fa-lg fa-rotate mx-1"></i>
              </div>
            <% end %>
          </div>
          <div class="nav-horizontal-scroll" data-controller="nav-scroll-into-view" data-nav-scroll-into-view-target="filter" data-nav-scroll-into-view-category-value="<%= params[:category] %>">
            <div class="container nav-list" data-nav-scroll-into-view-target="filterLinks" >
              <% Workout::WORKOUT_EMOJIS.each do |key, value|%>
                <%= link_to value, workouts_path(category: key), class: 'btn btn-ghost'%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <% if @search_copy %>
        <div class="container-content bg-none text-primary my-0 py-0">
          <h2 class=""><%= @search_copy %></h2>
        </div>
      <% end %>
      <% unless @workouts.present? %>
        <p class="text-start"> There are no results for your search 💔 </p>
      <% end %>
      <% if @workouts.present? %>
        <div class="container-workouts">
          <% @workouts.each do |workout| %>
            <div class="card-workout">
              <%= link_to workout_path(workout), class: "text-decoration-none" do %>
                <%= cl_image_tag workout.photo.key %>
                <div class="card-workout-infos">
                  <div style="width: 80%">
                    <h2><%= workout.activity_type %></h2>
                    <p><% workout.intensity_level.times do %>
                      <%= '💪' %>
                    <% end %></p>
                    <p><i class="fa-solid fa-calendar text-primary pe-1"></i> <%= workout.start_time.strftime("%H:%M") %> <%= workout.date.strftime("%e %h %Y") %></p>
                    <p><i class="fa-solid fa-map-pin text-primary pe-2"></i> <%= workout.location %></p>

                  </div>
                  <p class="duration-pill-box"><%= workout.duration %> mins</p>
                  <%= cl_image_tag workout.user.photo.key, class: "card-workout-user card-avatar" %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <%# PAGE WITH MAP %>
    <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
      <div class="d-flex flex-column bd-highlight mb-2">
        <div class="container-white-map-page">
          <div style="width: 100%; height: 80vh;"
            data-controller="map"
            data-map-markers-value="<%= @workout_location.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render "shared/navbar_footer" %>

app/views/workouts/my_workouts.html.erb
<% provide(:title, "My Workouts") %>

<div class="banner-my-workouts" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://hult-center-assets.s3.amazonaws.com/uploads/2022/07/Running-WebBanner-2100x700-1-1800x600.jpg)">
  <h1>Your Workouts</h1>
</div>
<div class="container pb-5 mb-4">

  <div class="container-white p-1">
    <div class="container">
      <h2>Your schedule </h2>
    </div>
    <% @upcoming_workouts.each do |workout| %>
      <% host = workout.user %>
      <% has_booking = workout.bookings.first.present? %>
      <% guest = has_booking ? workout.bookings.first.user : "buddy" %>
      <% buddy = (workout.user == current_user ? guest : host)  %>
      <%= link_to workout_path(workout), style: "color: #2C302E;", class: "text-decoration-none" do %>
        <div class="d-flex flex-row justify-content-between card-my-workouts">
          <div>
            <%= cl_image_tag workout.photo.key, height: 80, width: 80, crop: "fill" %>
          </div>
          <div class="ps-2", style="width: 5%">
            <% if current_user == host %>
              <i class="fa-solid fa-sm fa-pen-to-square"></i>
            <% end %>
          </div>
          <div class="flex-fill card-my-workouts-info">
            <h2><%= workout.activity_type %><%= has_booking ? " with " + buddy.first_name : "" %></h2>
            <p class="m-0"><%= workout.date.strftime("%e %h %Y") %>, <%= workout.start_time.strftime("%H") %>:00</p>
          </div>
          <div class="p-1">
            <%# <% unless workout.user == current_user %>
              <%# <%= cl_image_tag workout.user.photo.key, class: "p-2", height: 72, width: 72, radius: "max", crop: "fill", gravity: "face" %>
            <%# <% end %>
            <% if has_booking && current_user == host %>
              <%= cl_image_tag buddy.photo.key, class: "p-2", height: 72, width: 72, radius: "max", crop: "fill", gravity: "face" %>
            <% elsif workout.user != current_user %>
              <%= cl_image_tag workout.user.photo.key, class: "p-2", height: 72, width: 72, radius: "max", crop: "fill", gravity: "face" %>
            <% else %>
              <%= image_tag "Go-transparent.png", class: "p-2", height: 72, width: 72, radius: "max", crop: "fill" %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <% if @past_workouts.present? %>
    <div class="container-white p-1">
      <div class="container mt-1">
        <h2>History </h2>
      </div>
    <% end %>
    <% @past_workouts.each do |workout| %>
      <% host = workout.user %>
      <% has_booking = workout.bookings.first.present? %>
      <% guest = has_booking ? workout.bookings.first.user : "buddy" %>
      <% buddy = (workout.user == current_user ? guest : host)  %>
      <%= link_to workout_path(workout), style: "color: #2C302E;", class: "text-decoration-none" do %>
        <div class="d-flex flex-row justify-content-between card-my-workouts">
          <div>
            <%= cl_image_tag workout.photo.key, height: 80, width: 80, crop: "fill" %>
          </div>
          <div class="ps-2", style="width: 5%">
          </div>
          <div class="flex-fill card-my-workouts-info">
            <h2><%= workout.activity_type %><%= has_booking ? " with " + buddy.first_name : "" %></h2>
            <p class="m-0"><%= workout.date.strftime("%e %h %Y") %>, <%= workout.start_time.strftime("%H") %>:00</p>
          </div>
          <div class="p-1">
            <% unless workout.user == current_user %>
              <%= cl_image_tag workout.user.photo.key, class: "p-2", height: 72, width: 72, radius: "max", crop: "fill", gravity: "face" %>
            <% end %>
            <% if has_booking && current_user == host %>
              <%= cl_image_tag buddy.photo.key , class: "p-2", height: 72, width: 72, radius: "max", crop: "fill", gravity: "face" %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<%= render "shared/navbar_footer" %>

app/views/workouts/new.html.erb
<% provide(:title, "Add Workout") %>

<div class="banner-my-workouts" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://hult-center-assets.s3.amazonaws.com/uploads/2022/07/Running-WebBanner-2100x700-1-1800x600.jpg)">
  <div class="back-button">
    <%= link_to workouts_path do %>
      <div>
        <i class="fa-solid fa-arrow-left"></i>
      </div>
    <% end %>
  </div>
  <h1>Add Workout</h1>
</div>
<div class="container-white mt-3 mx-3 mb-5 pb-3">
  <div class="">
    <%= render "form", workout: @workout %>
  </div>
</div>
<%= render "shared/navbar_footer" %>

app/views/workouts/show.html.erb
<% provide(:title, @workout.activity_type) %>

<div class="banner-my-workouts"
  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @workout.photo.key, crop: :fill %>')"
>
  <div class="back-button">
    <%= link_to workouts_path do %>
      <div>
        <i class="fa-solid fa-arrow-left"></i>
      </div>
    <% end %>
  </div>
  <h1><%= @workout.activity_type %></h1>
</div>

<div class="container pb-5 mb-4">
  <div class="container-white">
    <div class="container-content">
      <div class="d-flex flex-row justify-content-around">
        <div class="flex-fill">
          <% if @workout.is_host?(current_user) %>
            <% if @workout.has_a_booking? %>
              <h3>Joined by <%= link_to @workout.name_of_buddy(current_user), user_path(@workout.bookings.first.user.id), style: "text-decoration: none" %></h3>
            <% end %>
          <% end %>

          <% unless @workout.is_host?(current_user) %>
            <h3>Hosted by <%= link_to @workout.name_of_buddy(current_user), user_path(@workout.user.id), style: "text-decoration: none" %></h3>
          <% end %>
        </div>
        <div class="flex-shrink-0">
          <% if @workout.has_a_booking? %>
            <%= link_to booking_chat_path(@workout.bookings.first.id, @workout.workout_chat.first.id) do %>
              <div>
                <i class="fa-regular fa-lg fa-message"></i>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>

      <% if @workout.ask_for_rating?(current_user) %>
        <div class="container-yellow">
          <div class="d-flex align-items-center justify-content-between mt-1">
            <div class="flex-fill">
              <h3>How was it?</h3>
            </div>
            <div class="btn-group" role="group" aria-label="Did buddy attend buttons">
              <button type="button" class="btn btn-outline-primary bg-light me-1" data-bs-toggle="modal" data-bs-target="#feedbackModal"> 👎 </button>
              <button type="button" class="btn btn-outline-primary bg-primary" data-bs-toggle="modal" data-bs-target="#feedbackModal"> 👍 </button>
            </div>
          </div>
        </div>
        <!-- Feedback Modal -->
        <div class="modal fade" id="feedbackModal" tabindex="-1" aria-labelledby="feedbackModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="feedbackModalLabel">How was the <%= @workout.activity_type %> with <%= @workout.name_of_buddy(current_user) %>?</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body" >
                <%= render "ratings/form", workout: @workout, booking: @workout.bookings.first, rating: @rating %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <% if @workout.has_a_rating? %>
        <% @workout.ratings.each do |rating| %>
          <div class="container-content text-center">
            <p><% rating.buddy_rating.times do %>
              <%= '⭐️' %>
            <% end %><br>
            <%= rating.comment %><br></p>
            <h6><%= rating.user.first_name %></h6>
        </div>
        <% end %>
      <% end %>
    </div>

    <div class="container-content">
      <div class="d-flex flex-row justify-content-between">
        <div class="flex-fill">
          <h4>Workout details</h4>
        </div>
        <div class="align-self-center mx-2">
          <% if @workout.is_host?(current_user) && !@workout.date.past? %>
            <%= link_to edit_workout_path(@workout.id) do %>
              <div>
                  <i class="fa-solid fa-sm fa-pen-to-square"></i>
              </div>
            <% end %>
          <% end %>
        </div>
        <div class="align-self-center mx-2">
          <% if @workout.is_host?(current_user) && !@workout.date.past? %>
            <%= link_to workout_path(@workout.id),
                data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                  <div>
                    <i class="fa-solid fa-sm fa-trash"></i>
                  </div>
            <% end %>
          <% end %>
          <% unless @workout.is_host?(current_user) || @workout.date.past? %>
            <% if @workout.has_a_booking? %>
              <%= link_to booking_path(@workout.bookings.first.id), style: "text-decoration: none;",
              data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to cancel this booking?"} do %>
                <div>
                  <i class="fa-solid fa-lg fa-xmark"></i> Cancel
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
      <p><%=  @workout.description.capitalize %></p>

      <div class="d-flex flex-row justify-content-between">
        <div>
          <h5><i-calendar class="fa-solid fa-calendar text-primary"></i> </h5>
        </div>
        <div class="flex-fill text-start">
          <p><%= @workout.date.strftime("%e %h %Y") %>, <%= @workout.start_time.strftime("%H:%M") %></p>
        </div>
      </div>
      <div class="d-flex flex-row justify-content-between">
        <div>
          <h5><i-clock class="fa-solid fa-clock text-primary"></i> </h5>
        </div>
        <div class="flex-fill text-start">
          <p><%= @workout.duration %> (mins)</p>
        </div>
      </div>
      <div class="d-flex flex-row justify-content-between">
        <div>
          <h5><i-pin class="fa-solid fa-map-pin text-primary"></i> </h5>
        </div>
        <div class="flex-fill text-start">
          <p><%= @workout.location%></p>
        </div>
      </div>
      <% if !@workout.has_a_booking? && !@workout.is_host?(current_user) %>
        <%= render "bookings/form", workout: @workout, booking: @booking %>
      <% end %>
    </div>
    <div class="container-content">
      <div class="show-page-map"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY']%>">
      </div>
    </div>
  <% if @workout.is_host?(current_user) %>
    <% if @workout.has_a_booking? %>
      <div class="container-content">
        <%= link_to user_path(@workout.buddy(current_user)), style: "color: #2C302E; text-decoration: none;" do %>
          <div class="d-flex flex-row justify-content-between">
            <div class="flex-fill pe-1">
              <h4>Meet <%= @workout.name_of_buddy(current_user) %></h4>
              <p><%= @workout.name_of_buddy(current_user) %> joined <span style="color: $fern-green">Let's Go</span> in <%= @user.created_at.strftime("%b %y") %><br>
              A little about them: <%= @workout.buddy(current_user).about_me.truncate(30) %></p>
            </div>
            <div class="align-self-center">
              <%= cl_image_tag @workout.buddy(current_user).photo.key, class: "avatar-large" %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

    <% unless @workout.has_a_booking? %>
      <div class="container-content">
        <div class="d-flex flex-row justify-content-between">
          <div class="flex-fill">
            <h4>Space available 🤗</h4>
            <p></p>
          </div>
          <div class="align-self-center">
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

  <% unless @workout.is_host?(current_user) %>
    <div class="container-yellow">
      <%= link_to user_path(@user), style: "color: #2C302E; text-decoration: none;" do %>
        <div class="d-flex flex-row justify-content-between">
          <div class="flex-fill">
            <h4>Check out <%= @workout.user.first_name.capitalize %>'s profile</h4>
            <p><%= @workout.user.first_name.capitalize %> joined <span style="color: $fern-green">Let's Go</span> in <%= @user.created_at.strftime("%b %y") %><br>
            A little about them: <%= @workout.user.about_me.truncate(30) %></p>
          </div>
          <div class="align-self-center">
            <%= cl_image_tag @workout.user.photo.key, class: "avatar-large" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  </div>
  <%= render "shared/navbar_footer" %>
</div>