config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Custom routes
  get "workouts/my_workouts", to: "workouts#my_workouts"

  # Application routes
  resources :workouts, only: %i[index new create show destroy edit update] do
    resources :bookings, only: %i[new create] do
      resources :ratings, only: %i[new create]
    end
  end
  resources :users, only: [:show]
  resources :chats, only: [:index]

  resources :bookings, only: %i[index show destroy edit update] do
    resources :ratings, only: %i[new create]
    resources :chats, only: %i[show] do
      resources :messages, only: :create
    end
  end
end

# Defines the root path route ("/")
# root "articles#index"

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :workout
  has_many :ratings, dependent: :destroy
  has_one :chat, dependent: :destroy

  after_create :create_chat

  scope :with_ratings, -> { joins(:ratings) }

  def self.create_chat
    @chat = Chat.create!(booking_id: booking)
  end

  def self.ratings_by_others(logged_in_user)
    Rating.where(id: all.with_ratings.where.not('ratings.user_id' => logged_in_user.id).pluck('ratings.id'))
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_user, only: %i[new create index show]
  before_action :set_workout, only: %i[new create]
  before_action :set_rating, only: %i[show]

  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new
    @booking.user = @user
    @booking.workout_id = @workout.id
    @booking.booking_date = @workout.date
    if @booking.save!
      redirect_to workout_path(@workout)
    else
      render "workouts/show", status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])

    if @booking.destroy!
      redirect_to workouts_path, status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def set_workout
    @workout = Workout.find(params[:workout_id])
  end

  def set_chat
    @chat = Chat.find(params[:chat_id])
  end

  def set_rating
    @rating = Rating.new
  end

  def booking_params
    params.require(:booking).permit(:user_id, :workout_id, :booking_date)
  end
end

app/views/bookings/_form.html.erb
<%= simple_form_for([workout, Booking.new]) do |f| %>
  <%= f.submit "Join #{workout.user.first_name.capitalize}", class: "button-design" %>
<% end %>

app/views/bookings/index.html.erb
<div class="container">
  <h2>This is the booking index page</h2>
  <% @bookings.each do |booking| %>
    <%= link_to booking.booking_date, booking_path(booking) %><br>
  <% end %>
</div>
<%= render "shared/navbar_footer" %>

app/views/bookings/show.html.erb
<div class="container">
<div class="container-white">

  <%= link_to bookings_path do %>
      <div>
        <i class="fa-solid fa-arrow-left"></i>
      </div>
    <% end %>
  <br><br>
<div>
  <h1>Congratulations! 🎉🎉🎉🎉🎉</h1>
  <h1>You've booked a <%= @booking.workout.activity_type %> with <%= @booking.workout.user.first_name %></h1>
  <br>
  <strong>Your workout is on: </strong><%= @booking.booking_date.strftime("%e %h %Y") %>
    <% if current_user == @booking.user %>
      <%= link_to booking_path(@booking),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
        <div>
          <i class="fa-solid fa-xmark"></i>
        </div>
      <% end %>
    <% end %>

  <%= link_to "View #{@booking.workout.user.first_name}'s workout", workout_path(@booking.workout_id), class: "btn btn-ghost" %>

  <br>
  <%= link_to "View #{@booking.workout.user.first_name}'s profile", user_path(@booking.workout.user), class: "btn btn-ghost" %>

  <br>
  <%= link_to "Message #{@booking.workout.user.first_name}", user_path(@booking.workout.user), class: "btn btn-ghost" %>
  <%= link_to "Message #{@booking.workout.user.first_name}", booking_chat_path(@booking.id, @booking.chat.id), class: "button-design-small-font" %>
  <br><br>
</div>
  <h3>Ratings</h3>
  <% if @booking.ratings.empty? %>
    <p class="text-start"> There are no ratings yet 💔 </p>
  <% else %>

    <p class="text-start"> Your buddy's rating: <%= @booking.ratings.first.buddy_rating %><br>
    <p class="text-start"> Your buddy's review: <%= @booking.ratings.first.comment %><br>
  <% end %>

  <% @booking.ratings.each do |rating| %>
    <p><strong>Rating ID: </strong><%= rating.id %><br>
    <strong>Your name: </strong><%= rating.booking.user.first_name %><br>
    <strong>Did buddy attend: </strong><%= rating.buddy_attended %><br>
    <strong>You rated your buddy: </strong><%= rating.buddy_rating %><br>
    <strong>Comment: </strong><%= rating.comment %><br></p>
  <% end %>
  <br><br>
  <br><br>
</div>
<%= render "shared/navbar_footer" %>
</div>